# Generated by Django 5.1.2 on 2024-11-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Введите название страны",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        help_text="Введите ИНН", max_length=50, verbose_name="ИНН"
                    ),
                ),
                (
                    "address",
                    models.TextField(help_text="Введите адрес", verbose_name="Адрес"),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "ordering": ["country"],
            },
        ),
    ]
